config/routes.rb
Rails.application.routes.draw do
  resources :addresses do
    collection do
      get :states
    end
  end
  resources :tweets do
    resources :likes
  end
  resources :posts do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  broadcasts_to :post  # create update destroy will broadcast to post
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title
  has_rich_text :content
  has_many :comments, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :body, presence: true

  after_create_commit { broadcast_prepend_to 'tweets' }
  after_update_commit { broadcast_replace_to 'tweets' }
  after_destroy_commit { broadcast_remove_to 'tweets' }
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: %i[show edit update destroy]

  # GET /addresses or /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1 or /addresses/1.json
  def show; end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit; end

  # POST /addresses or /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to address_url(@address), notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1 or /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to address_url(@address), notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @address.destroy

    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def states
    @target = params[:target]
    @states = CS.get(params[:country]).invert
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_address
    @address = Address.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def address_params
    params.require(:address).permit(:country, :state)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    comment = @post.comments.create! params.required(:comment).permit(:content) # magic
    CommentsMailer.submitted(comment).deliver_later # will use async job queue. Q: what is the default queue?
    redirect_to @post
  end

  private

  def set_post
    @post = Post.find params[:post_id]
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_tweet

  def create
    @tweet.increment! :likes_count
    redirect_to @tweet # returns show _tweet which contains a turbo_frame_tag, allowing this to be called in a turbo frame tag
  end

  private

  def set_tweet
    @tweet = Tweet.find params[:tweet_id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[show edit update destroy]

  # GET /tweets or /tweets.json
  def index
    @tweet = Tweet.new
    @tweets = Tweet.all
  end

  # GET /tweets/1 or /tweets/1.json
  def show; end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit; end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_url, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        # turbo_stream is responding to the ajax request from turbo_frame_tag
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('tweet_form', partial: 'tweets/form', locals: { tweet: @tweet })
        end
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@tweet) }
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tweet_params
    params.require(:tweet).permit(:body, :likes_count, :retweets_count)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/addresses/_address.html.erb
<div id="<%= dom_id address %>">
  <p>
    <strong>Country:</strong>
    <%= address.country %>
  </p>

  <p>
    <strong>State:</strong>
    <%= address.state %>
  </p>

</div>

app/views/addresses/_form.html.erb
<%= form_with(model: address) do |form| %>
  <% if address.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
        <% address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div data-controller="select" data-select-url-value="<%= states_addresses_path %>" data-select-param-value="country">
    <div>
      <%= form.label :country, style: "display: block" %>
      <%= form.select :country, CS.countries.invert, { prompt: 'Select a country'}, { class: 'form-control', data: { action: 'change->select#change'} }%>
    </div>

    <div>
      <%= form.label :state, style: "display: block" %>
      <%= form.select :state, [], {}, { id: nil, class: 'form-control', data: { select_target: 'select' } }%>
    </div>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render "form", address: @address %>

<br>

<div>
  <%= link_to "Show this address", @address %> |
  <%= link_to "Back to addresses", addresses_path %>
</div>

app/views/addresses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Addresses</h1>

<div id="addresses">
  <% @addresses.each do |address| %>
    <%= render address %>
    <p>
      <%= link_to "Show this address", address %>
    </p>
  <% end %>
</div>

<%= link_to "New address", new_address_path %>

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render "form", address: @address %>

<br>

<div>
  <%= link_to "Back to addresses", addresses_path %>
</div>

app/views/addresses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @address %>

<div>
  <%= link_to "Edit this address", edit_address_path(@address) %> |
  <%= link_to "Back to addresses", addresses_path %>

  <%= button_to "Destroy this address", @address, method: :delete %>
</div>

app/views/addresses/states.turbo_stream.erb
<%# We don't want to update turbo stream using classes, since it updates all elements with that class, instead we specify a "target" %>
<%= turbo_stream.update @target do %>
  <%= options_for_select @states %>
<% end %>

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>">
  <%= comment.content %>
  - <%= time_tag comment.created_at, "data-local": "time-ago" %>
</div>

app/views/comments/_new.html.erb
<%= form_with model: [@post, Comment.new] do |form| %>
  Your comment: <br>
  <%= form.text_area :content, size: '20x5' %>
  <%= form.submit %>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>R7demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_comments.html.erb
<h2>Comments</h2>

<div id="comments">
  <%# Expands to render partial: "comments/comment", collection: post.comments  %>
  <%= render post.comments %>
</div>

<%= render 'comments/new', post: post %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.rich_text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

  <p>
   <b><%= pluralize post.comments.count, "comment" %></b>
  </p>

  <p>
    <%# time_tag  %>
    <%# time-ago is used by local-time %>
    Posted <%= time_tag post.created_at, "data-local": "time-ago" %>
  </p>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<%= turbo_stream_from @post %>

<p style="color: green"><%= notice %></p>

<%= render @post %>
<%= render 'posts/comments', { post: @post } %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :likes_count, style: "display: block" %>
    <%= form.number_field :likes_count %>
  </div>

  <div>
    <%= form.label :retweets_count, style: "display: block" %>
    <%= form.number_field :retweets_count %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<%= turbo_frame_tag tweet do%>
  <div id="<%= dom_id tweet %>" class="card">
    <p>Body:<%= tweet.body %></p>
    <%= button_to "Likes #{tweet.likes_count || 0}", tweet_likes_path(tweet) %>
    <p>Retweets (<%= tweet.retweets_count %>)</p>
    <%= link_to "Edit", edit_tweet_path(tweet) %>
    <%= button_to "X", tweet_path(tweet), method: :delete %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= turbo_frame_tag dom_id(@tweet) do %>
  <div class="card">
    <%= render "form", tweet: @tweet %>
    <%# render show -> _tweet and there is a turbo_frame_tag in it %>
    <%= link_to "Cancel", tweet_path(@tweet) %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Add a tweet</h1>

<%# After wrapping with turbo frame, it submits the form using ajax for us. It also expects a turbo_stream response %>
<%= turbo_frame_tag 'tweet_form' do %>
  <%= render 'tweets/form', tweet: @tweet %>
<% end %>

<h1>Tweets</h1>

<%= turbo_stream_from 'tweets' %>

<%= turbo_frame_tag 'tweets' do %>
  <%= render @tweets %>
<% end %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Back to tweets", tweets_path %>

  <%= button_to "Destroy this tweet", @tweet, method: :delete %>
</div>